[package]
name = "image-preprocessing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.5.0"
zip = "2.2.0"
kamadak-exif = "0.5.5"
image = "0.25.2"



